apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sklearn-iris
spec:
  predictor:
    serviceAccountName: sa
    sklearn:
      runtimeVersion: 1.3.5
      protocolVersion: v2
      storageUri: "s3://[BUCKET NAME]/clearml/MASTER-CLASS/Iris/[YOUR TASK NAME].[YOUR TASK ID]/models"