name: clearml_experiments
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - blas=1.0
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - fftw=3.3.9
  - libcxx=14.0.6
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libxgboost=1.5.0
  - lightgbm=3.1.1
  - llvm-openmp=14.0.6
  - ncurses=6.3
  - numpy-base=1.23.4
  - openssl=1.1.1s
  - pip=22.2.2
  - py-xgboost=1.5.0
  - python=3.8.15
  - readline=8.2
  - scikit-learn=1.1.3
  - setuptools=65.5.0
  - sqlite=3.40.0
  - tk=8.6.12
  - wheel=0.37.1
  - xgboost=1.5.0
  - xz=5.2.8
  - zlib=1.2.13
  - pip:
    - attrs==22.1.0
    - boto3==1.26.24
    - botocore==1.29.24
    - charset-normalizer==2.1.1
    - clearml==1.8.3
    - contourpy==1.0.6
    - cycler==0.11.0
    - fonttools==4.38.0
    - furl==2.1.3
    - idna==3.4
    - importlib-resources==5.10.1
    - jmespath==1.0.1
    - joblib==1.2.0
    - jsonschema==4.17.3
    - kiwisolver==1.4.4
    - matplotlib==3.6.2
    - numpy==1.23.5
    - orderedmultidict==1.0.1
    - packaging==21.3
    - pandas==1.5.2
    - pathlib2==2.3.7.post1
    - pillow==9.3.0
    - pkgutil-resolve-name==1.3.10
    - psutil==5.9.4
    - pyjwt==2.4.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.2
    - python-dateutil==2.8.2
    - pytz==2022.6
    - requests==2.28.1
    - s3transfer==0.6.0
    - scipy==1.9.3
    - six==1.16.0
    - threadpoolctl==3.1.0
    - urllib3==1.26.13
    - zipp==3.11.0
